/**
 *
 *  RestfulMomentLikeCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulMomentLikeCtrl.h"
#include <string>


void RestfulMomentLikeCtrl::getOne(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback,
                                   MomentLike::PrimaryKeyType &&id)
{
    RestfulMomentLikeCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulMomentLikeCtrl::updateOne(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback,
                                      MomentLike::PrimaryKeyType &&id)
{
    RestfulMomentLikeCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulMomentLikeCtrl::deleteOne(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback,
                                      MomentLike::PrimaryKeyType &&id)
{
    RestfulMomentLikeCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulMomentLikeCtrl::get(const HttpRequestPtr &req,
                                std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulMomentLikeCtrlBase::get(req, std::move(callback));
}

void RestfulMomentLikeCtrl::create(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulMomentLikeCtrlBase::create(req, std::move(callback));
}
