/**
 *
 *  RestfulFriendRequestCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulFriendRequestCtrl.h"
#include <string>


void RestfulFriendRequestCtrl::getOne(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback,
                                      FriendRequest::PrimaryKeyType &&id)
{
    RestfulFriendRequestCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulFriendRequestCtrl::updateOne(const HttpRequestPtr &req,
                                         std::function<void(const HttpResponsePtr &)> &&callback,
                                         FriendRequest::PrimaryKeyType &&id)
{
    RestfulFriendRequestCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulFriendRequestCtrl::deleteOne(const HttpRequestPtr &req,
                                         std::function<void(const HttpResponsePtr &)> &&callback,
                                         FriendRequest::PrimaryKeyType &&id)
{
    RestfulFriendRequestCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulFriendRequestCtrl::get(const HttpRequestPtr &req,
                                   std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulFriendRequestCtrlBase::get(req, std::move(callback));
}

void RestfulFriendRequestCtrl::create(const HttpRequestPtr &req,
                                      std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulFriendRequestCtrlBase::create(req, std::move(callback));
}
