/**
 *
 *  RestfulOfflineMessageCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulOfflineMessageCtrl.h"
#include <string>


void RestfulOfflineMessageCtrl::getOne(const HttpRequestPtr &req,
                                       std::function<void(const HttpResponsePtr &)> &&callback,
                                       OfflineMessage::PrimaryKeyType &&id)
{
    RestfulOfflineMessageCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulOfflineMessageCtrl::updateOne(const HttpRequestPtr &req,
                                          std::function<void(const HttpResponsePtr &)> &&callback,
                                          OfflineMessage::PrimaryKeyType &&id)
{
    RestfulOfflineMessageCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulOfflineMessageCtrl::deleteOne(const HttpRequestPtr &req,
                                          std::function<void(const HttpResponsePtr &)> &&callback,
                                          OfflineMessage::PrimaryKeyType &&id)
{
    RestfulOfflineMessageCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulOfflineMessageCtrl::get(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulOfflineMessageCtrlBase::get(req, std::move(callback));
}

void RestfulOfflineMessageCtrl::create(const HttpRequestPtr &req,
                                       std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulOfflineMessageCtrlBase::create(req, std::move(callback));
}
