/**
 *
 *  RestfulGroupMemberCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulGroupMemberCtrl.h"
#include <string>


void RestfulGroupMemberCtrl::getOne(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback,
                                    GroupMember::PrimaryKeyType &&id)
{
    RestfulGroupMemberCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulGroupMemberCtrl::updateOne(const HttpRequestPtr &req,
                                       std::function<void(const HttpResponsePtr &)> &&callback,
                                       GroupMember::PrimaryKeyType &&id)
{
    RestfulGroupMemberCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulGroupMemberCtrl::deleteOne(const HttpRequestPtr &req,
                                       std::function<void(const HttpResponsePtr &)> &&callback,
                                       GroupMember::PrimaryKeyType &&id)
{
    RestfulGroupMemberCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulGroupMemberCtrl::get(const HttpRequestPtr &req,
                                 std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulGroupMemberCtrlBase::get(req, std::move(callback));
}

void RestfulGroupMemberCtrl::create(const HttpRequestPtr &req,
                                    std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulGroupMemberCtrlBase::create(req, std::move(callback));
}
