/**
 *
 *  RestfulDeviceCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "RestfulDeviceCtrl.h"
#include <string>


void RestfulDeviceCtrl::getOne(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback,
                               Device::PrimaryKeyType &&id)
{
    RestfulDeviceCtrlBase::getOne(req, std::move(callback), std::move(id));
}


void RestfulDeviceCtrl::updateOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Device::PrimaryKeyType &&id)
{
    RestfulDeviceCtrlBase::updateOne(req, std::move(callback), std::move(id));
}


void RestfulDeviceCtrl::deleteOne(const HttpRequestPtr &req,
                                  std::function<void(const HttpResponsePtr &)> &&callback,
                                  Device::PrimaryKeyType &&id)
{
    RestfulDeviceCtrlBase::deleteOne(req, std::move(callback), std::move(id));
}

void RestfulDeviceCtrl::get(const HttpRequestPtr &req,
                            std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulDeviceCtrlBase::get(req, std::move(callback));
}

void RestfulDeviceCtrl::create(const HttpRequestPtr &req,
                               std::function<void(const HttpResponsePtr &)> &&callback)
{
    RestfulDeviceCtrlBase::create(req, std::move(callback));
}
