/**
 *
 *  RestfulMomentLikeCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulMomentLikeCtrlBase.h"

#include "MomentLike.h"
using namespace drogon;
using namespace drogon_model::yaroserverdb;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the moment_like table.
 */

class RestfulMomentLikeCtrl: public drogon::HttpController<RestfulMomentLikeCtrl>, public RestfulMomentLikeCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulMomentLikeCtrl::getOne,"/api/v1/momentlike/{1}",Get,Options,"JwtFilter");
    ADD_METHOD_TO(RestfulMomentLikeCtrl::updateOne,"/api/v1/momentlike/{1}",Put,Options,"JwtFilter");
    ADD_METHOD_TO(RestfulMomentLikeCtrl::deleteOne,"/api/v1/momentlike/{1}",Delete,Options,"JwtFilter");
    ADD_METHOD_TO(RestfulMomentLikeCtrl::get,"/api/v1/momentlike",Get,Options,"JwtFilter");
    ADD_METHOD_TO(RestfulMomentLikeCtrl::create,"/api/v1/momentlike",Post,Options,"JwtFilter");
    //ADD_METHOD_TO(RestfulMomentLikeCtrl::update,"/api/v1/momentlike",Put,Options,"JwtFilter");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                MomentLike::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   MomentLike::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   MomentLike::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
