/**
 *
 *  RestfulUserCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulUserCtrlBase.h"

#include "User.h"
using namespace drogon;
using namespace drogon_model::yaroserverdb;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the user table.
 */

class RestfulUserCtrl: public drogon::HttpController<RestfulUserCtrl>, public RestfulUserCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulUserCtrl::getOne,"/api/v1/user/{1}",Get,Options,"JwtFilter");
    ADD_METHOD_TO(RestfulUserCtrl::updateOne,"/api/v1/user/{1}",Put,Options,"JwtFilter");
    ADD_METHOD_TO(RestfulUserCtrl::deleteOne,"/api/v1/user/{1}",Delete,Options,"JwtFilter");
    ADD_METHOD_TO(RestfulUserCtrl::get,"/api/v1/user",Get,Options,"JwtFilter");
    ADD_METHOD_TO(RestfulUserCtrl::create,"/api/v1/user",Post,Options,"JwtFilter");
    //ADD_METHOD_TO(RestfulUserCtrl::update,"/api/v1/user",Put,Options,"JwtFilter");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                User::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   User::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   User::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
