/**
 *
 *  RestfulFriendRequestCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulFriendRequestCtrlBase.h"

#include "FriendRequest.h"
using namespace drogon;
using namespace drogon_model::yaroserverdb;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the friend_request table.
 */

class RestfulFriendRequestCtrl: public drogon::HttpController<RestfulFriendRequestCtrl>, public RestfulFriendRequestCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulFriendRequestCtrl::getOne,"/api/v1/friendrequest/{1}",Get,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulFriendRequestCtrl::updateOne,"/api/v1/friendrequest/{1}",Put,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulFriendRequestCtrl::deleteOne,"/api/v1/friendrequest/{1}",Delete,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulFriendRequestCtrl::get,"/api/v1/friendrequest",Get,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulFriendRequestCtrl::create,"/api/v1/friendrequest",Post,Options,"AuthFilter");
    //ADD_METHOD_TO(RestfulFriendRequestCtrl::update,"/api/v1/friendrequest",Put,Options,"AuthFilter");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                FriendRequest::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   FriendRequest::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   FriendRequest::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
