/**
 *
 *  RestfulFriendCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulFriendCtrlBase.h"

#include "Friend.h"
using namespace drogon;
using namespace drogon_model::yaroserverdb;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the friend table.
 */

class RestfulFriendCtrl: public drogon::HttpController<RestfulFriendCtrl>, public RestfulFriendCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulFriendCtrl::getOne,"/api/v1/friend/{1}",Get,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulFriendCtrl::updateOne,"/api/v1/friend/{1}",Put,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulFriendCtrl::deleteOne,"/api/v1/friend/{1}",Delete,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulFriendCtrl::get,"/api/v1/friend",Get,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulFriendCtrl::create,"/api/v1/friend",Post,Options,"AuthFilter");
    //ADD_METHOD_TO(RestfulFriendCtrl::update,"/api/v1/friend",Put,Options,"AuthFilter");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Friend::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Friend::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Friend::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
