/**
 *
 *  RestfulMomentCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulMomentCtrlBase.h"

#include "Moment.h"
using namespace drogon;
using namespace drogon_model::yaroserverdb;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the moment table.
 */

class RestfulMomentCtrl: public drogon::HttpController<RestfulMomentCtrl>, public RestfulMomentCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulMomentCtrl::getOne,"/api/v1/moment/{1}",Get,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulMomentCtrl::updateOne,"/api/v1/moment/{1}",Put,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulMomentCtrl::deleteOne,"/api/v1/moment/{1}",Delete,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulMomentCtrl::get,"/api/v1/moment",Get,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulMomentCtrl::create,"/api/v1/moment",Post,Options,"AuthFilter");
    //ADD_METHOD_TO(RestfulMomentCtrl::update,"/api/v1/moment",Put,Options,"AuthFilter");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Moment::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Moment::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Moment::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
