/**
 *
 *  RestfulGroupCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulGroupCtrlBase.h"

#include "Group.h"
using namespace drogon;
using namespace drogon_model::yaroserverdb;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the group table.
 */

class RestfulGroupCtrl: public drogon::HttpController<RestfulGroupCtrl>, public RestfulGroupCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulGroupCtrl::getOne,"/api/v1/group/{1}",Get,Options,"JwtFilter");
    ADD_METHOD_TO(RestfulGroupCtrl::updateOne,"/api/v1/group/{1}",Put,Options,"JwtFilter");
    ADD_METHOD_TO(RestfulGroupCtrl::deleteOne,"/api/v1/group/{1}",Delete,Options,"JwtFilter");
    ADD_METHOD_TO(RestfulGroupCtrl::get,"/api/v1/group",Get,Options,"JwtFilter");
    ADD_METHOD_TO(RestfulGroupCtrl::create,"/api/v1/group",Post,Options,"JwtFilter");
    //ADD_METHOD_TO(RestfulGroupCtrl::update,"/api/v1/group",Put,Options,"JwtFilter");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                Group::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Group::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   Group::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
