/**
 *
 *  RestfulGroupMemberCtrl.h
 *  This file is generated by drogon_ctl
 *
 */

#pragma once

#include <drogon/HttpController.h>
#include "RestfulGroupMemberCtrlBase.h"

#include "GroupMember.h"
using namespace drogon;
using namespace drogon_model::yaroserverdb;
/**
 * @brief this class is created by the drogon_ctl command.
 * this class is a restful API controller for reading and writing the group_member table.
 */

class RestfulGroupMemberCtrl: public drogon::HttpController<RestfulGroupMemberCtrl>, public RestfulGroupMemberCtrlBase
{
  public:
    METHOD_LIST_BEGIN
    ADD_METHOD_TO(RestfulGroupMemberCtrl::getOne,"/api/v1/groupmember/{1}",Get,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulGroupMemberCtrl::updateOne,"/api/v1/groupmember/{1}",Put,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulGroupMemberCtrl::deleteOne,"/api/v1/groupmember/{1}",Delete,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulGroupMemberCtrl::get,"/api/v1/groupmember",Get,Options,"AuthFilter");
    ADD_METHOD_TO(RestfulGroupMemberCtrl::create,"/api/v1/groupmember",Post,Options,"AuthFilter");
    //ADD_METHOD_TO(RestfulGroupMemberCtrl::update,"/api/v1/groupmember",Put,Options,"AuthFilter");
    METHOD_LIST_END
     
    void getOne(const HttpRequestPtr &req,
                std::function<void(const HttpResponsePtr &)> &&callback,
                GroupMember::PrimaryKeyType &&id);
    void updateOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   GroupMember::PrimaryKeyType &&id);
    void deleteOne(const HttpRequestPtr &req,
                   std::function<void(const HttpResponsePtr &)> &&callback,
                   GroupMember::PrimaryKeyType &&id);
    void get(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);
    void create(const HttpRequestPtr &req,
             std::function<void(const HttpResponsePtr &)> &&callback);

};
