/**
 *
 *  Group.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace yaroserverdb
{
class GroupMember;
class User;

class Group
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _group_name;
        static const std::string _avatar_url;
        static const std::string _announcement;
        static const std::string _introduction;
        static const std::string _owner_id;
        static const std::string _max_members;
        static const std::string _join_type;
        static const std::string _status;
        static const std::string _created_at;
        static const std::string _updated_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Group(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Group(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Group(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Group() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;

    /**  For column group_name  */
    ///Get the value of the column group_name, returns the default value if the column is null
    const std::string &getValueOfGroupName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getGroupName() const noexcept;
    ///Set the value of the column group_name
    void setGroupName(const std::string &pGroupName) noexcept;
    void setGroupName(std::string &&pGroupName) noexcept;

    /**  For column avatar_url  */
    ///Get the value of the column avatar_url, returns the default value if the column is null
    const std::string &getValueOfAvatarUrl() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAvatarUrl() const noexcept;
    ///Set the value of the column avatar_url
    void setAvatarUrl(const std::string &pAvatarUrl) noexcept;
    void setAvatarUrl(std::string &&pAvatarUrl) noexcept;
    void setAvatarUrlToNull() noexcept;

    /**  For column announcement  */
    ///Get the value of the column announcement, returns the default value if the column is null
    const std::string &getValueOfAnnouncement() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAnnouncement() const noexcept;
    ///Set the value of the column announcement
    void setAnnouncement(const std::string &pAnnouncement) noexcept;
    void setAnnouncement(std::string &&pAnnouncement) noexcept;
    void setAnnouncementToNull() noexcept;

    /**  For column introduction  */
    ///Get the value of the column introduction, returns the default value if the column is null
    const std::string &getValueOfIntroduction() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getIntroduction() const noexcept;
    ///Set the value of the column introduction
    void setIntroduction(const std::string &pIntroduction) noexcept;
    void setIntroduction(std::string &&pIntroduction) noexcept;
    void setIntroductionToNull() noexcept;

    /**  For column owner_id  */
    ///Get the value of the column owner_id, returns the default value if the column is null
    const int64_t &getValueOfOwnerId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getOwnerId() const noexcept;
    ///Set the value of the column owner_id
    void setOwnerId(const int64_t &pOwnerId) noexcept;

    /**  For column max_members  */
    ///Get the value of the column max_members, returns the default value if the column is null
    const int32_t &getValueOfMaxMembers() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getMaxMembers() const noexcept;
    ///Set the value of the column max_members
    void setMaxMembers(const int32_t &pMaxMembers) noexcept;
    void setMaxMembersToNull() noexcept;

    /**  For column join_type  */
    ///Get the value of the column join_type, returns the default value if the column is null
    const int8_t &getValueOfJoinType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int8_t> &getJoinType() const noexcept;
    ///Set the value of the column join_type
    void setJoinType(const int8_t &pJoinType) noexcept;
    void setJoinTypeToNull() noexcept;

    /**  For column status  */
    ///Get the value of the column status, returns the default value if the column is null
    const int8_t &getValueOfStatus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int8_t> &getStatus() const noexcept;
    ///Set the value of the column status
    void setStatus(const int8_t &pStatus) noexcept;
    void setStatusToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;
    void setCreatedAtToNull() noexcept;

    /**  For column updated_at  */
    ///Get the value of the column updated_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdatedAt() const noexcept;
    ///Set the value of the column updated_at
    void setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept;
    void setUpdatedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 11;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    User getUser(const drogon::orm::DbClientPtr &clientPtr) const;
    void getUser(const drogon::orm::DbClientPtr &clientPtr,
                 const std::function<void(User)> &rcb,
                 const drogon::orm::ExceptionCallback &ecb) const;
    std::vector<GroupMember> getGroupMember(const drogon::orm::DbClientPtr &clientPtr) const;
    void getGroupMember(const drogon::orm::DbClientPtr &clientPtr,
                        const std::function<void(std::vector<GroupMember>)> &rcb,
                        const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<Group>;
    friend drogon::orm::BaseBuilder<Group, true, true>;
    friend drogon::orm::BaseBuilder<Group, true, false>;
    friend drogon::orm::BaseBuilder<Group, false, true>;
    friend drogon::orm::BaseBuilder<Group, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Group>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<std::string> groupName_;
    std::shared_ptr<std::string> avatarUrl_;
    std::shared_ptr<std::string> announcement_;
    std::shared_ptr<std::string> introduction_;
    std::shared_ptr<int64_t> ownerId_;
    std::shared_ptr<int32_t> maxMembers_;
    std::shared_ptr<int8_t> joinType_;
    std::shared_ptr<int8_t> status_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<::trantor::Date> updatedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[11]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "group_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "avatar_url,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "announcement,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "introduction,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "owner_id,";
            ++parametersCount;
        }
        sql += "max_members,";
        ++parametersCount;
        if(!dirtyFlag_[6])
        {
            needSelection=true;
        }
        sql += "join_type,";
        ++parametersCount;
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        sql += "status,";
        ++parametersCount;
        if(!dirtyFlag_[8])
        {
            needSelection=true;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[9])
        {
            needSelection=true;
        }
        sql += "updated_at,";
        ++parametersCount;
        if(!dirtyFlag_[10])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        sql +="default,";
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[9])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[10])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace yaroserverdb
} // namespace drogon_model
