/**
 *
 *  Group.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Group.h"
#include "GroupMember.h"
#include "User.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::yaroserverdb;

const std::string Group::Cols::_id = "id";
const std::string Group::Cols::_group_name = "group_name";
const std::string Group::Cols::_avatar_url = "avatar_url";
const std::string Group::Cols::_announcement = "announcement";
const std::string Group::Cols::_introduction = "introduction";
const std::string Group::Cols::_owner_id = "owner_id";
const std::string Group::Cols::_max_members = "max_members";
const std::string Group::Cols::_join_type = "join_type";
const std::string Group::Cols::_status = "status";
const std::string Group::Cols::_created_at = "created_at";
const std::string Group::Cols::_updated_at = "updated_at";
const std::string Group::primaryKeyName = "id";
const bool Group::hasPrimaryKey = true;
const std::string Group::tableName = "group";

const std::vector<typename Group::MetaData> Group::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"group_name","std::string","varchar(100)",100,0,0,1},
{"avatar_url","std::string","varchar(255)",255,0,0,0},
{"announcement","std::string","text",0,0,0,0},
{"introduction","std::string","varchar(500)",500,0,0,0},
{"owner_id","int64_t","bigint",8,0,0,1},
{"max_members","int32_t","int",4,0,0,0},
{"join_type","int8_t","tinyint",1,0,0,0},
{"status","int8_t","tinyint",1,0,0,0},
{"created_at","::trantor::Date","datetime",0,0,0,0},
{"updated_at","::trantor::Date","datetime",0,0,0,0}
};
const std::string &Group::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Group::Group(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["group_name"].isNull())
        {
            groupName_=std::make_shared<std::string>(r["group_name"].as<std::string>());
        }
        if(!r["avatar_url"].isNull())
        {
            avatarUrl_=std::make_shared<std::string>(r["avatar_url"].as<std::string>());
        }
        if(!r["announcement"].isNull())
        {
            announcement_=std::make_shared<std::string>(r["announcement"].as<std::string>());
        }
        if(!r["introduction"].isNull())
        {
            introduction_=std::make_shared<std::string>(r["introduction"].as<std::string>());
        }
        if(!r["owner_id"].isNull())
        {
            ownerId_=std::make_shared<int64_t>(r["owner_id"].as<int64_t>());
        }
        if(!r["max_members"].isNull())
        {
            maxMembers_=std::make_shared<int32_t>(r["max_members"].as<int32_t>());
        }
        if(!r["join_type"].isNull())
        {
            joinType_=std::make_shared<int8_t>(r["join_type"].as<int8_t>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<int8_t>(r["status"].as<int8_t>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["updated_at"].isNull())
        {
            auto timeStr = r["updated_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 11 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            groupName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            avatarUrl_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            announcement_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            introduction_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            ownerId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            maxMembers_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            joinType_=std::make_shared<int8_t>(r[index].as<int8_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            status_=std::make_shared<int8_t>(r[index].as<int8_t>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

Group::Group(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            groupName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            avatarUrl_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            announcement_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            introduction_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            ownerId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            maxMembers_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            joinType_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            status_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

Group::Group(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("group_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["group_name"].isNull())
        {
            groupName_=std::make_shared<std::string>(pJson["group_name"].asString());
        }
    }
    if(pJson.isMember("avatar_url"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["avatar_url"].isNull())
        {
            avatarUrl_=std::make_shared<std::string>(pJson["avatar_url"].asString());
        }
    }
    if(pJson.isMember("announcement"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["announcement"].isNull())
        {
            announcement_=std::make_shared<std::string>(pJson["announcement"].asString());
        }
    }
    if(pJson.isMember("introduction"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["introduction"].isNull())
        {
            introduction_=std::make_shared<std::string>(pJson["introduction"].asString());
        }
    }
    if(pJson.isMember("owner_id"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["owner_id"].isNull())
        {
            ownerId_=std::make_shared<int64_t>((int64_t)pJson["owner_id"].asInt64());
        }
    }
    if(pJson.isMember("max_members"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["max_members"].isNull())
        {
            maxMembers_=std::make_shared<int32_t>((int32_t)pJson["max_members"].asInt64());
        }
    }
    if(pJson.isMember("join_type"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["join_type"].isNull())
        {
            joinType_=std::make_shared<int8_t>((int8_t)pJson["join_type"].asInt64());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<int8_t>((int8_t)pJson["status"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Group::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            groupName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            avatarUrl_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            announcement_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            introduction_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            ownerId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            maxMembers_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            joinType_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            status_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[10]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Group::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("group_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["group_name"].isNull())
        {
            groupName_=std::make_shared<std::string>(pJson["group_name"].asString());
        }
    }
    if(pJson.isMember("avatar_url"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["avatar_url"].isNull())
        {
            avatarUrl_=std::make_shared<std::string>(pJson["avatar_url"].asString());
        }
    }
    if(pJson.isMember("announcement"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["announcement"].isNull())
        {
            announcement_=std::make_shared<std::string>(pJson["announcement"].asString());
        }
    }
    if(pJson.isMember("introduction"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["introduction"].isNull())
        {
            introduction_=std::make_shared<std::string>(pJson["introduction"].asString());
        }
    }
    if(pJson.isMember("owner_id"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["owner_id"].isNull())
        {
            ownerId_=std::make_shared<int64_t>((int64_t)pJson["owner_id"].asInt64());
        }
    }
    if(pJson.isMember("max_members"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["max_members"].isNull())
        {
            maxMembers_=std::make_shared<int32_t>((int32_t)pJson["max_members"].asInt64());
        }
    }
    if(pJson.isMember("join_type"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["join_type"].isNull())
        {
            joinType_=std::make_shared<int8_t>((int8_t)pJson["join_type"].asInt64());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<int8_t>((int8_t)pJson["status"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("updated_at"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["updated_at"].isNull())
        {
            auto timeStr = pJson["updated_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                updatedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &Group::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Group::getId() const noexcept
{
    return id_;
}
void Group::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Group::PrimaryKeyType & Group::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Group::getValueOfGroupName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(groupName_)
        return *groupName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Group::getGroupName() const noexcept
{
    return groupName_;
}
void Group::setGroupName(const std::string &pGroupName) noexcept
{
    groupName_ = std::make_shared<std::string>(pGroupName);
    dirtyFlag_[1] = true;
}
void Group::setGroupName(std::string &&pGroupName) noexcept
{
    groupName_ = std::make_shared<std::string>(std::move(pGroupName));
    dirtyFlag_[1] = true;
}

const std::string &Group::getValueOfAvatarUrl() const noexcept
{
    static const std::string defaultValue = std::string();
    if(avatarUrl_)
        return *avatarUrl_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Group::getAvatarUrl() const noexcept
{
    return avatarUrl_;
}
void Group::setAvatarUrl(const std::string &pAvatarUrl) noexcept
{
    avatarUrl_ = std::make_shared<std::string>(pAvatarUrl);
    dirtyFlag_[2] = true;
}
void Group::setAvatarUrl(std::string &&pAvatarUrl) noexcept
{
    avatarUrl_ = std::make_shared<std::string>(std::move(pAvatarUrl));
    dirtyFlag_[2] = true;
}
void Group::setAvatarUrlToNull() noexcept
{
    avatarUrl_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Group::getValueOfAnnouncement() const noexcept
{
    static const std::string defaultValue = std::string();
    if(announcement_)
        return *announcement_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Group::getAnnouncement() const noexcept
{
    return announcement_;
}
void Group::setAnnouncement(const std::string &pAnnouncement) noexcept
{
    announcement_ = std::make_shared<std::string>(pAnnouncement);
    dirtyFlag_[3] = true;
}
void Group::setAnnouncement(std::string &&pAnnouncement) noexcept
{
    announcement_ = std::make_shared<std::string>(std::move(pAnnouncement));
    dirtyFlag_[3] = true;
}
void Group::setAnnouncementToNull() noexcept
{
    announcement_.reset();
    dirtyFlag_[3] = true;
}

const std::string &Group::getValueOfIntroduction() const noexcept
{
    static const std::string defaultValue = std::string();
    if(introduction_)
        return *introduction_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Group::getIntroduction() const noexcept
{
    return introduction_;
}
void Group::setIntroduction(const std::string &pIntroduction) noexcept
{
    introduction_ = std::make_shared<std::string>(pIntroduction);
    dirtyFlag_[4] = true;
}
void Group::setIntroduction(std::string &&pIntroduction) noexcept
{
    introduction_ = std::make_shared<std::string>(std::move(pIntroduction));
    dirtyFlag_[4] = true;
}
void Group::setIntroductionToNull() noexcept
{
    introduction_.reset();
    dirtyFlag_[4] = true;
}

const int64_t &Group::getValueOfOwnerId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(ownerId_)
        return *ownerId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Group::getOwnerId() const noexcept
{
    return ownerId_;
}
void Group::setOwnerId(const int64_t &pOwnerId) noexcept
{
    ownerId_ = std::make_shared<int64_t>(pOwnerId);
    dirtyFlag_[5] = true;
}

const int32_t &Group::getValueOfMaxMembers() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(maxMembers_)
        return *maxMembers_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Group::getMaxMembers() const noexcept
{
    return maxMembers_;
}
void Group::setMaxMembers(const int32_t &pMaxMembers) noexcept
{
    maxMembers_ = std::make_shared<int32_t>(pMaxMembers);
    dirtyFlag_[6] = true;
}
void Group::setMaxMembersToNull() noexcept
{
    maxMembers_.reset();
    dirtyFlag_[6] = true;
}

const int8_t &Group::getValueOfJoinType() const noexcept
{
    static const int8_t defaultValue = int8_t();
    if(joinType_)
        return *joinType_;
    return defaultValue;
}
const std::shared_ptr<int8_t> &Group::getJoinType() const noexcept
{
    return joinType_;
}
void Group::setJoinType(const int8_t &pJoinType) noexcept
{
    joinType_ = std::make_shared<int8_t>(pJoinType);
    dirtyFlag_[7] = true;
}
void Group::setJoinTypeToNull() noexcept
{
    joinType_.reset();
    dirtyFlag_[7] = true;
}

const int8_t &Group::getValueOfStatus() const noexcept
{
    static const int8_t defaultValue = int8_t();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<int8_t> &Group::getStatus() const noexcept
{
    return status_;
}
void Group::setStatus(const int8_t &pStatus) noexcept
{
    status_ = std::make_shared<int8_t>(pStatus);
    dirtyFlag_[8] = true;
}
void Group::setStatusToNull() noexcept
{
    status_.reset();
    dirtyFlag_[8] = true;
}

const ::trantor::Date &Group::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Group::getCreatedAt() const noexcept
{
    return createdAt_;
}
void Group::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[9] = true;
}
void Group::setCreatedAtToNull() noexcept
{
    createdAt_.reset();
    dirtyFlag_[9] = true;
}

const ::trantor::Date &Group::getValueOfUpdatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(updatedAt_)
        return *updatedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Group::getUpdatedAt() const noexcept
{
    return updatedAt_;
}
void Group::setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept
{
    updatedAt_ = std::make_shared<::trantor::Date>(pUpdatedAt);
    dirtyFlag_[10] = true;
}
void Group::setUpdatedAtToNull() noexcept
{
    updatedAt_.reset();
    dirtyFlag_[10] = true;
}

void Group::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &Group::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "group_name",
        "avatar_url",
        "announcement",
        "introduction",
        "owner_id",
        "max_members",
        "join_type",
        "status",
        "created_at",
        "updated_at"
    };
    return inCols;
}

void Group::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getGroupName())
        {
            binder << getValueOfGroupName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAvatarUrl())
        {
            binder << getValueOfAvatarUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getAnnouncement())
        {
            binder << getValueOfAnnouncement();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getIntroduction())
        {
            binder << getValueOfIntroduction();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getOwnerId())
        {
            binder << getValueOfOwnerId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMaxMembers())
        {
            binder << getValueOfMaxMembers();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getJoinType())
        {
            binder << getValueOfJoinType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Group::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    return ret;
}

void Group::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getGroupName())
        {
            binder << getValueOfGroupName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAvatarUrl())
        {
            binder << getValueOfAvatarUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getAnnouncement())
        {
            binder << getValueOfAnnouncement();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getIntroduction())
        {
            binder << getValueOfIntroduction();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getOwnerId())
        {
            binder << getValueOfOwnerId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getMaxMembers())
        {
            binder << getValueOfMaxMembers();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getJoinType())
        {
            binder << getValueOfJoinType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getUpdatedAt())
        {
            binder << getValueOfUpdatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Group::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getGroupName())
    {
        ret["group_name"]=getValueOfGroupName();
    }
    else
    {
        ret["group_name"]=Json::Value();
    }
    if(getAvatarUrl())
    {
        ret["avatar_url"]=getValueOfAvatarUrl();
    }
    else
    {
        ret["avatar_url"]=Json::Value();
    }
    if(getAnnouncement())
    {
        ret["announcement"]=getValueOfAnnouncement();
    }
    else
    {
        ret["announcement"]=Json::Value();
    }
    if(getIntroduction())
    {
        ret["introduction"]=getValueOfIntroduction();
    }
    else
    {
        ret["introduction"]=Json::Value();
    }
    if(getOwnerId())
    {
        ret["owner_id"]=(Json::Int64)getValueOfOwnerId();
    }
    else
    {
        ret["owner_id"]=Json::Value();
    }
    if(getMaxMembers())
    {
        ret["max_members"]=getValueOfMaxMembers();
    }
    else
    {
        ret["max_members"]=Json::Value();
    }
    if(getJoinType())
    {
        ret["join_type"]=getValueOfJoinType();
    }
    else
    {
        ret["join_type"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

std::string Group::toString() const
{
    return toJson().toStyledString();
}

Json::Value Group::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 11)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getGroupName())
            {
                ret[pMasqueradingVector[1]]=getValueOfGroupName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getAvatarUrl())
            {
                ret[pMasqueradingVector[2]]=getValueOfAvatarUrl();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getAnnouncement())
            {
                ret[pMasqueradingVector[3]]=getValueOfAnnouncement();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getIntroduction())
            {
                ret[pMasqueradingVector[4]]=getValueOfIntroduction();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getOwnerId())
            {
                ret[pMasqueradingVector[5]]=(Json::Int64)getValueOfOwnerId();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getMaxMembers())
            {
                ret[pMasqueradingVector[6]]=getValueOfMaxMembers();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getJoinType())
            {
                ret[pMasqueradingVector[7]]=getValueOfJoinType();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[8]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[9]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getUpdatedAt())
            {
                ret[pMasqueradingVector[10]]=getUpdatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getGroupName())
    {
        ret["group_name"]=getValueOfGroupName();
    }
    else
    {
        ret["group_name"]=Json::Value();
    }
    if(getAvatarUrl())
    {
        ret["avatar_url"]=getValueOfAvatarUrl();
    }
    else
    {
        ret["avatar_url"]=Json::Value();
    }
    if(getAnnouncement())
    {
        ret["announcement"]=getValueOfAnnouncement();
    }
    else
    {
        ret["announcement"]=Json::Value();
    }
    if(getIntroduction())
    {
        ret["introduction"]=getValueOfIntroduction();
    }
    else
    {
        ret["introduction"]=Json::Value();
    }
    if(getOwnerId())
    {
        ret["owner_id"]=(Json::Int64)getValueOfOwnerId();
    }
    else
    {
        ret["owner_id"]=Json::Value();
    }
    if(getMaxMembers())
    {
        ret["max_members"]=getValueOfMaxMembers();
    }
    else
    {
        ret["max_members"]=Json::Value();
    }
    if(getJoinType())
    {
        ret["join_type"]=getValueOfJoinType();
    }
    else
    {
        ret["join_type"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getUpdatedAt())
    {
        ret["updated_at"]=getUpdatedAt()->toDbStringLocal();
    }
    else
    {
        ret["updated_at"]=Json::Value();
    }
    return ret;
}

bool Group::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("group_name"))
    {
        if(!validJsonOfField(1, "group_name", pJson["group_name"], err, true))
            return false;
    }
    else
    {
        err="The group_name column cannot be null";
        return false;
    }
    if(pJson.isMember("avatar_url"))
    {
        if(!validJsonOfField(2, "avatar_url", pJson["avatar_url"], err, true))
            return false;
    }
    if(pJson.isMember("announcement"))
    {
        if(!validJsonOfField(3, "announcement", pJson["announcement"], err, true))
            return false;
    }
    if(pJson.isMember("introduction"))
    {
        if(!validJsonOfField(4, "introduction", pJson["introduction"], err, true))
            return false;
    }
    if(pJson.isMember("owner_id"))
    {
        if(!validJsonOfField(5, "owner_id", pJson["owner_id"], err, true))
            return false;
    }
    else
    {
        err="The owner_id column cannot be null";
        return false;
    }
    if(pJson.isMember("max_members"))
    {
        if(!validJsonOfField(6, "max_members", pJson["max_members"], err, true))
            return false;
    }
    if(pJson.isMember("join_type"))
    {
        if(!validJsonOfField(7, "join_type", pJson["join_type"], err, true))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(8, "status", pJson["status"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(9, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(10, "updated_at", pJson["updated_at"], err, true))
            return false;
    }
    return true;
}
bool Group::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Group::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("group_name"))
    {
        if(!validJsonOfField(1, "group_name", pJson["group_name"], err, false))
            return false;
    }
    if(pJson.isMember("avatar_url"))
    {
        if(!validJsonOfField(2, "avatar_url", pJson["avatar_url"], err, false))
            return false;
    }
    if(pJson.isMember("announcement"))
    {
        if(!validJsonOfField(3, "announcement", pJson["announcement"], err, false))
            return false;
    }
    if(pJson.isMember("introduction"))
    {
        if(!validJsonOfField(4, "introduction", pJson["introduction"], err, false))
            return false;
    }
    if(pJson.isMember("owner_id"))
    {
        if(!validJsonOfField(5, "owner_id", pJson["owner_id"], err, false))
            return false;
    }
    if(pJson.isMember("max_members"))
    {
        if(!validJsonOfField(6, "max_members", pJson["max_members"], err, false))
            return false;
    }
    if(pJson.isMember("join_type"))
    {
        if(!validJsonOfField(7, "join_type", pJson["join_type"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(8, "status", pJson["status"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(9, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("updated_at"))
    {
        if(!validJsonOfField(10, "updated_at", pJson["updated_at"], err, false))
            return false;
    }
    return true;
}
bool Group::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Group::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 500)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 500)";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
User Group::getUser(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from user where id = ?";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *ownerId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return User(r[0]);
}

void Group::getUser(const DbClientPtr &clientPtr,
                    const std::function<void(User)> &rcb,
                    const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from user where id = ?";
    *clientPtr << sql
               << *ownerId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(User(r[0]));
                    }
               }
               >> ecb;
}
std::vector<GroupMember> Group::getGroupMember(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from group_member where group_id = ?";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *id_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<GroupMember> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(GroupMember(row));
    }
    return ret;
}

void Group::getGroupMember(const DbClientPtr &clientPtr,
                           const std::function<void(std::vector<GroupMember>)> &rcb,
                           const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from group_member where group_id = ?";
    *clientPtr << sql
               << *id_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<GroupMember> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(GroupMember(row));
                   }
                   rcb(ret);
               }
               >> ecb;
}
