/**
 *
 *  OfflineMessage.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "OfflineMessage.h"
#include "User.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::yaroserverdb;

const std::string OfflineMessage::Cols::_id = "id";
const std::string OfflineMessage::Cols::_from_user_id = "from_user_id";
const std::string OfflineMessage::Cols::_to_user_id = "to_user_id";
const std::string OfflineMessage::Cols::_chat_type = "chat_type";
const std::string OfflineMessage::Cols::_target_id = "target_id";
const std::string OfflineMessage::Cols::_msg_type = "msg_type";
const std::string OfflineMessage::Cols::_content = "content";
const std::string OfflineMessage::Cols::_media_url = "media_url";
const std::string OfflineMessage::Cols::_media_thumb_url = "media_thumb_url";
const std::string OfflineMessage::Cols::_media_size = "media_size";
const std::string OfflineMessage::Cols::_media_duration = "media_duration";
const std::string OfflineMessage::Cols::_media_format = "media_format";
const std::string OfflineMessage::Cols::_created_at = "created_at";
const std::string OfflineMessage::Cols::_expire_time = "expire_time";
const std::string OfflineMessage::primaryKeyName = "id";
const bool OfflineMessage::hasPrimaryKey = true;
const std::string OfflineMessage::tableName = "offline_message";

const std::vector<typename OfflineMessage::MetaData> OfflineMessage::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"from_user_id","int64_t","bigint",8,0,0,1},
{"to_user_id","int64_t","bigint",8,0,0,1},
{"chat_type","int8_t","tinyint",1,0,0,1},
{"target_id","int64_t","bigint",8,0,0,1},
{"msg_type","int8_t","tinyint",1,0,0,1},
{"content","std::string","text",0,0,0,0},
{"media_url","std::string","varchar(255)",255,0,0,0},
{"media_thumb_url","std::string","varchar(255)",255,0,0,0},
{"media_size","int64_t","bigint",8,0,0,0},
{"media_duration","int32_t","int",4,0,0,0},
{"media_format","std::string","varchar(20)",20,0,0,0},
{"created_at","::trantor::Date","datetime",0,0,0,0},
{"expire_time","::trantor::Date","datetime",0,0,0,0}
};
const std::string &OfflineMessage::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
OfflineMessage::OfflineMessage(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["from_user_id"].isNull())
        {
            fromUserId_=std::make_shared<int64_t>(r["from_user_id"].as<int64_t>());
        }
        if(!r["to_user_id"].isNull())
        {
            toUserId_=std::make_shared<int64_t>(r["to_user_id"].as<int64_t>());
        }
        if(!r["chat_type"].isNull())
        {
            chatType_=std::make_shared<int8_t>(r["chat_type"].as<int8_t>());
        }
        if(!r["target_id"].isNull())
        {
            targetId_=std::make_shared<int64_t>(r["target_id"].as<int64_t>());
        }
        if(!r["msg_type"].isNull())
        {
            msgType_=std::make_shared<int8_t>(r["msg_type"].as<int8_t>());
        }
        if(!r["content"].isNull())
        {
            content_=std::make_shared<std::string>(r["content"].as<std::string>());
        }
        if(!r["media_url"].isNull())
        {
            mediaUrl_=std::make_shared<std::string>(r["media_url"].as<std::string>());
        }
        if(!r["media_thumb_url"].isNull())
        {
            mediaThumbUrl_=std::make_shared<std::string>(r["media_thumb_url"].as<std::string>());
        }
        if(!r["media_size"].isNull())
        {
            mediaSize_=std::make_shared<int64_t>(r["media_size"].as<int64_t>());
        }
        if(!r["media_duration"].isNull())
        {
            mediaDuration_=std::make_shared<int32_t>(r["media_duration"].as<int32_t>());
        }
        if(!r["media_format"].isNull())
        {
            mediaFormat_=std::make_shared<std::string>(r["media_format"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["expire_time"].isNull())
        {
            auto timeStr = r["expire_time"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 14 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            fromUserId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            toUserId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            chatType_=std::make_shared<int8_t>(r[index].as<int8_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            targetId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            msgType_=std::make_shared<int8_t>(r[index].as<int8_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            content_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            mediaUrl_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            mediaThumbUrl_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            mediaSize_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            mediaDuration_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            mediaFormat_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

OfflineMessage::OfflineMessage(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            fromUserId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            toUserId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            chatType_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            targetId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            msgType_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            content_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            mediaUrl_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            mediaThumbUrl_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            mediaSize_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            mediaDuration_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            mediaFormat_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[13]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

OfflineMessage::OfflineMessage(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("from_user_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["from_user_id"].isNull())
        {
            fromUserId_=std::make_shared<int64_t>((int64_t)pJson["from_user_id"].asInt64());
        }
    }
    if(pJson.isMember("to_user_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["to_user_id"].isNull())
        {
            toUserId_=std::make_shared<int64_t>((int64_t)pJson["to_user_id"].asInt64());
        }
    }
    if(pJson.isMember("chat_type"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["chat_type"].isNull())
        {
            chatType_=std::make_shared<int8_t>((int8_t)pJson["chat_type"].asInt64());
        }
    }
    if(pJson.isMember("target_id"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["target_id"].isNull())
        {
            targetId_=std::make_shared<int64_t>((int64_t)pJson["target_id"].asInt64());
        }
    }
    if(pJson.isMember("msg_type"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["msg_type"].isNull())
        {
            msgType_=std::make_shared<int8_t>((int8_t)pJson["msg_type"].asInt64());
        }
    }
    if(pJson.isMember("content"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["content"].isNull())
        {
            content_=std::make_shared<std::string>(pJson["content"].asString());
        }
    }
    if(pJson.isMember("media_url"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["media_url"].isNull())
        {
            mediaUrl_=std::make_shared<std::string>(pJson["media_url"].asString());
        }
    }
    if(pJson.isMember("media_thumb_url"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["media_thumb_url"].isNull())
        {
            mediaThumbUrl_=std::make_shared<std::string>(pJson["media_thumb_url"].asString());
        }
    }
    if(pJson.isMember("media_size"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["media_size"].isNull())
        {
            mediaSize_=std::make_shared<int64_t>((int64_t)pJson["media_size"].asInt64());
        }
    }
    if(pJson.isMember("media_duration"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["media_duration"].isNull())
        {
            mediaDuration_=std::make_shared<int32_t>((int32_t)pJson["media_duration"].asInt64());
        }
    }
    if(pJson.isMember("media_format"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["media_format"].isNull())
        {
            mediaFormat_=std::make_shared<std::string>(pJson["media_format"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("expire_time"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["expire_time"].isNull())
        {
            auto timeStr = pJson["expire_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void OfflineMessage::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            fromUserId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            toUserId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            chatType_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            targetId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            msgType_=std::make_shared<int8_t>((int8_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            content_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            mediaUrl_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            mediaThumbUrl_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            mediaSize_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            mediaDuration_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            mediaFormat_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[12]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[13]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void OfflineMessage::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("from_user_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["from_user_id"].isNull())
        {
            fromUserId_=std::make_shared<int64_t>((int64_t)pJson["from_user_id"].asInt64());
        }
    }
    if(pJson.isMember("to_user_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["to_user_id"].isNull())
        {
            toUserId_=std::make_shared<int64_t>((int64_t)pJson["to_user_id"].asInt64());
        }
    }
    if(pJson.isMember("chat_type"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["chat_type"].isNull())
        {
            chatType_=std::make_shared<int8_t>((int8_t)pJson["chat_type"].asInt64());
        }
    }
    if(pJson.isMember("target_id"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["target_id"].isNull())
        {
            targetId_=std::make_shared<int64_t>((int64_t)pJson["target_id"].asInt64());
        }
    }
    if(pJson.isMember("msg_type"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["msg_type"].isNull())
        {
            msgType_=std::make_shared<int8_t>((int8_t)pJson["msg_type"].asInt64());
        }
    }
    if(pJson.isMember("content"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["content"].isNull())
        {
            content_=std::make_shared<std::string>(pJson["content"].asString());
        }
    }
    if(pJson.isMember("media_url"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["media_url"].isNull())
        {
            mediaUrl_=std::make_shared<std::string>(pJson["media_url"].asString());
        }
    }
    if(pJson.isMember("media_thumb_url"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["media_thumb_url"].isNull())
        {
            mediaThumbUrl_=std::make_shared<std::string>(pJson["media_thumb_url"].asString());
        }
    }
    if(pJson.isMember("media_size"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["media_size"].isNull())
        {
            mediaSize_=std::make_shared<int64_t>((int64_t)pJson["media_size"].asInt64());
        }
    }
    if(pJson.isMember("media_duration"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["media_duration"].isNull())
        {
            mediaDuration_=std::make_shared<int32_t>((int32_t)pJson["media_duration"].asInt64());
        }
    }
    if(pJson.isMember("media_format"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["media_format"].isNull())
        {
            mediaFormat_=std::make_shared<std::string>(pJson["media_format"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("expire_time"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["expire_time"].isNull())
        {
            auto timeStr = pJson["expire_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                expireTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &OfflineMessage::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &OfflineMessage::getId() const noexcept
{
    return id_;
}
void OfflineMessage::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename OfflineMessage::PrimaryKeyType & OfflineMessage::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &OfflineMessage::getValueOfFromUserId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(fromUserId_)
        return *fromUserId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &OfflineMessage::getFromUserId() const noexcept
{
    return fromUserId_;
}
void OfflineMessage::setFromUserId(const int64_t &pFromUserId) noexcept
{
    fromUserId_ = std::make_shared<int64_t>(pFromUserId);
    dirtyFlag_[1] = true;
}

const int64_t &OfflineMessage::getValueOfToUserId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(toUserId_)
        return *toUserId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &OfflineMessage::getToUserId() const noexcept
{
    return toUserId_;
}
void OfflineMessage::setToUserId(const int64_t &pToUserId) noexcept
{
    toUserId_ = std::make_shared<int64_t>(pToUserId);
    dirtyFlag_[2] = true;
}

const int8_t &OfflineMessage::getValueOfChatType() const noexcept
{
    static const int8_t defaultValue = int8_t();
    if(chatType_)
        return *chatType_;
    return defaultValue;
}
const std::shared_ptr<int8_t> &OfflineMessage::getChatType() const noexcept
{
    return chatType_;
}
void OfflineMessage::setChatType(const int8_t &pChatType) noexcept
{
    chatType_ = std::make_shared<int8_t>(pChatType);
    dirtyFlag_[3] = true;
}

const int64_t &OfflineMessage::getValueOfTargetId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(targetId_)
        return *targetId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &OfflineMessage::getTargetId() const noexcept
{
    return targetId_;
}
void OfflineMessage::setTargetId(const int64_t &pTargetId) noexcept
{
    targetId_ = std::make_shared<int64_t>(pTargetId);
    dirtyFlag_[4] = true;
}

const int8_t &OfflineMessage::getValueOfMsgType() const noexcept
{
    static const int8_t defaultValue = int8_t();
    if(msgType_)
        return *msgType_;
    return defaultValue;
}
const std::shared_ptr<int8_t> &OfflineMessage::getMsgType() const noexcept
{
    return msgType_;
}
void OfflineMessage::setMsgType(const int8_t &pMsgType) noexcept
{
    msgType_ = std::make_shared<int8_t>(pMsgType);
    dirtyFlag_[5] = true;
}

const std::string &OfflineMessage::getValueOfContent() const noexcept
{
    static const std::string defaultValue = std::string();
    if(content_)
        return *content_;
    return defaultValue;
}
const std::shared_ptr<std::string> &OfflineMessage::getContent() const noexcept
{
    return content_;
}
void OfflineMessage::setContent(const std::string &pContent) noexcept
{
    content_ = std::make_shared<std::string>(pContent);
    dirtyFlag_[6] = true;
}
void OfflineMessage::setContent(std::string &&pContent) noexcept
{
    content_ = std::make_shared<std::string>(std::move(pContent));
    dirtyFlag_[6] = true;
}
void OfflineMessage::setContentToNull() noexcept
{
    content_.reset();
    dirtyFlag_[6] = true;
}

const std::string &OfflineMessage::getValueOfMediaUrl() const noexcept
{
    static const std::string defaultValue = std::string();
    if(mediaUrl_)
        return *mediaUrl_;
    return defaultValue;
}
const std::shared_ptr<std::string> &OfflineMessage::getMediaUrl() const noexcept
{
    return mediaUrl_;
}
void OfflineMessage::setMediaUrl(const std::string &pMediaUrl) noexcept
{
    mediaUrl_ = std::make_shared<std::string>(pMediaUrl);
    dirtyFlag_[7] = true;
}
void OfflineMessage::setMediaUrl(std::string &&pMediaUrl) noexcept
{
    mediaUrl_ = std::make_shared<std::string>(std::move(pMediaUrl));
    dirtyFlag_[7] = true;
}
void OfflineMessage::setMediaUrlToNull() noexcept
{
    mediaUrl_.reset();
    dirtyFlag_[7] = true;
}

const std::string &OfflineMessage::getValueOfMediaThumbUrl() const noexcept
{
    static const std::string defaultValue = std::string();
    if(mediaThumbUrl_)
        return *mediaThumbUrl_;
    return defaultValue;
}
const std::shared_ptr<std::string> &OfflineMessage::getMediaThumbUrl() const noexcept
{
    return mediaThumbUrl_;
}
void OfflineMessage::setMediaThumbUrl(const std::string &pMediaThumbUrl) noexcept
{
    mediaThumbUrl_ = std::make_shared<std::string>(pMediaThumbUrl);
    dirtyFlag_[8] = true;
}
void OfflineMessage::setMediaThumbUrl(std::string &&pMediaThumbUrl) noexcept
{
    mediaThumbUrl_ = std::make_shared<std::string>(std::move(pMediaThumbUrl));
    dirtyFlag_[8] = true;
}
void OfflineMessage::setMediaThumbUrlToNull() noexcept
{
    mediaThumbUrl_.reset();
    dirtyFlag_[8] = true;
}

const int64_t &OfflineMessage::getValueOfMediaSize() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(mediaSize_)
        return *mediaSize_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &OfflineMessage::getMediaSize() const noexcept
{
    return mediaSize_;
}
void OfflineMessage::setMediaSize(const int64_t &pMediaSize) noexcept
{
    mediaSize_ = std::make_shared<int64_t>(pMediaSize);
    dirtyFlag_[9] = true;
}
void OfflineMessage::setMediaSizeToNull() noexcept
{
    mediaSize_.reset();
    dirtyFlag_[9] = true;
}

const int32_t &OfflineMessage::getValueOfMediaDuration() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(mediaDuration_)
        return *mediaDuration_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OfflineMessage::getMediaDuration() const noexcept
{
    return mediaDuration_;
}
void OfflineMessage::setMediaDuration(const int32_t &pMediaDuration) noexcept
{
    mediaDuration_ = std::make_shared<int32_t>(pMediaDuration);
    dirtyFlag_[10] = true;
}
void OfflineMessage::setMediaDurationToNull() noexcept
{
    mediaDuration_.reset();
    dirtyFlag_[10] = true;
}

const std::string &OfflineMessage::getValueOfMediaFormat() const noexcept
{
    static const std::string defaultValue = std::string();
    if(mediaFormat_)
        return *mediaFormat_;
    return defaultValue;
}
const std::shared_ptr<std::string> &OfflineMessage::getMediaFormat() const noexcept
{
    return mediaFormat_;
}
void OfflineMessage::setMediaFormat(const std::string &pMediaFormat) noexcept
{
    mediaFormat_ = std::make_shared<std::string>(pMediaFormat);
    dirtyFlag_[11] = true;
}
void OfflineMessage::setMediaFormat(std::string &&pMediaFormat) noexcept
{
    mediaFormat_ = std::make_shared<std::string>(std::move(pMediaFormat));
    dirtyFlag_[11] = true;
}
void OfflineMessage::setMediaFormatToNull() noexcept
{
    mediaFormat_.reset();
    dirtyFlag_[11] = true;
}

const ::trantor::Date &OfflineMessage::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &OfflineMessage::getCreatedAt() const noexcept
{
    return createdAt_;
}
void OfflineMessage::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[12] = true;
}
void OfflineMessage::setCreatedAtToNull() noexcept
{
    createdAt_.reset();
    dirtyFlag_[12] = true;
}

const ::trantor::Date &OfflineMessage::getValueOfExpireTime() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(expireTime_)
        return *expireTime_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &OfflineMessage::getExpireTime() const noexcept
{
    return expireTime_;
}
void OfflineMessage::setExpireTime(const ::trantor::Date &pExpireTime) noexcept
{
    expireTime_ = std::make_shared<::trantor::Date>(pExpireTime);
    dirtyFlag_[13] = true;
}
void OfflineMessage::setExpireTimeToNull() noexcept
{
    expireTime_.reset();
    dirtyFlag_[13] = true;
}

void OfflineMessage::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &OfflineMessage::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "from_user_id",
        "to_user_id",
        "chat_type",
        "target_id",
        "msg_type",
        "content",
        "media_url",
        "media_thumb_url",
        "media_size",
        "media_duration",
        "media_format",
        "created_at",
        "expire_time"
    };
    return inCols;
}

void OfflineMessage::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getFromUserId())
        {
            binder << getValueOfFromUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getToUserId())
        {
            binder << getValueOfToUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getChatType())
        {
            binder << getValueOfChatType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTargetId())
        {
            binder << getValueOfTargetId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getMsgType())
        {
            binder << getValueOfMsgType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getContent())
        {
            binder << getValueOfContent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getMediaUrl())
        {
            binder << getValueOfMediaUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getMediaThumbUrl())
        {
            binder << getValueOfMediaThumbUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getMediaSize())
        {
            binder << getValueOfMediaSize();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getMediaDuration())
        {
            binder << getValueOfMediaDuration();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getMediaFormat())
        {
            binder << getValueOfMediaFormat();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getExpireTime())
        {
            binder << getValueOfExpireTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> OfflineMessage::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    return ret;
}

void OfflineMessage::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getFromUserId())
        {
            binder << getValueOfFromUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getToUserId())
        {
            binder << getValueOfToUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getChatType())
        {
            binder << getValueOfChatType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getTargetId())
        {
            binder << getValueOfTargetId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getMsgType())
        {
            binder << getValueOfMsgType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getContent())
        {
            binder << getValueOfContent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getMediaUrl())
        {
            binder << getValueOfMediaUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getMediaThumbUrl())
        {
            binder << getValueOfMediaThumbUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getMediaSize())
        {
            binder << getValueOfMediaSize();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getMediaDuration())
        {
            binder << getValueOfMediaDuration();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getMediaFormat())
        {
            binder << getValueOfMediaFormat();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getExpireTime())
        {
            binder << getValueOfExpireTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value OfflineMessage::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getFromUserId())
    {
        ret["from_user_id"]=(Json::Int64)getValueOfFromUserId();
    }
    else
    {
        ret["from_user_id"]=Json::Value();
    }
    if(getToUserId())
    {
        ret["to_user_id"]=(Json::Int64)getValueOfToUserId();
    }
    else
    {
        ret["to_user_id"]=Json::Value();
    }
    if(getChatType())
    {
        ret["chat_type"]=getValueOfChatType();
    }
    else
    {
        ret["chat_type"]=Json::Value();
    }
    if(getTargetId())
    {
        ret["target_id"]=(Json::Int64)getValueOfTargetId();
    }
    else
    {
        ret["target_id"]=Json::Value();
    }
    if(getMsgType())
    {
        ret["msg_type"]=getValueOfMsgType();
    }
    else
    {
        ret["msg_type"]=Json::Value();
    }
    if(getContent())
    {
        ret["content"]=getValueOfContent();
    }
    else
    {
        ret["content"]=Json::Value();
    }
    if(getMediaUrl())
    {
        ret["media_url"]=getValueOfMediaUrl();
    }
    else
    {
        ret["media_url"]=Json::Value();
    }
    if(getMediaThumbUrl())
    {
        ret["media_thumb_url"]=getValueOfMediaThumbUrl();
    }
    else
    {
        ret["media_thumb_url"]=Json::Value();
    }
    if(getMediaSize())
    {
        ret["media_size"]=(Json::Int64)getValueOfMediaSize();
    }
    else
    {
        ret["media_size"]=Json::Value();
    }
    if(getMediaDuration())
    {
        ret["media_duration"]=getValueOfMediaDuration();
    }
    else
    {
        ret["media_duration"]=Json::Value();
    }
    if(getMediaFormat())
    {
        ret["media_format"]=getValueOfMediaFormat();
    }
    else
    {
        ret["media_format"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getExpireTime())
    {
        ret["expire_time"]=getExpireTime()->toDbStringLocal();
    }
    else
    {
        ret["expire_time"]=Json::Value();
    }
    return ret;
}

std::string OfflineMessage::toString() const
{
    return toJson().toStyledString();
}

Json::Value OfflineMessage::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 14)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getFromUserId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfFromUserId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getToUserId())
            {
                ret[pMasqueradingVector[2]]=(Json::Int64)getValueOfToUserId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getChatType())
            {
                ret[pMasqueradingVector[3]]=getValueOfChatType();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getTargetId())
            {
                ret[pMasqueradingVector[4]]=(Json::Int64)getValueOfTargetId();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getMsgType())
            {
                ret[pMasqueradingVector[5]]=getValueOfMsgType();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getContent())
            {
                ret[pMasqueradingVector[6]]=getValueOfContent();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getMediaUrl())
            {
                ret[pMasqueradingVector[7]]=getValueOfMediaUrl();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getMediaThumbUrl())
            {
                ret[pMasqueradingVector[8]]=getValueOfMediaThumbUrl();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getMediaSize())
            {
                ret[pMasqueradingVector[9]]=(Json::Int64)getValueOfMediaSize();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getMediaDuration())
            {
                ret[pMasqueradingVector[10]]=getValueOfMediaDuration();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getMediaFormat())
            {
                ret[pMasqueradingVector[11]]=getValueOfMediaFormat();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[12]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getExpireTime())
            {
                ret[pMasqueradingVector[13]]=getExpireTime()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getFromUserId())
    {
        ret["from_user_id"]=(Json::Int64)getValueOfFromUserId();
    }
    else
    {
        ret["from_user_id"]=Json::Value();
    }
    if(getToUserId())
    {
        ret["to_user_id"]=(Json::Int64)getValueOfToUserId();
    }
    else
    {
        ret["to_user_id"]=Json::Value();
    }
    if(getChatType())
    {
        ret["chat_type"]=getValueOfChatType();
    }
    else
    {
        ret["chat_type"]=Json::Value();
    }
    if(getTargetId())
    {
        ret["target_id"]=(Json::Int64)getValueOfTargetId();
    }
    else
    {
        ret["target_id"]=Json::Value();
    }
    if(getMsgType())
    {
        ret["msg_type"]=getValueOfMsgType();
    }
    else
    {
        ret["msg_type"]=Json::Value();
    }
    if(getContent())
    {
        ret["content"]=getValueOfContent();
    }
    else
    {
        ret["content"]=Json::Value();
    }
    if(getMediaUrl())
    {
        ret["media_url"]=getValueOfMediaUrl();
    }
    else
    {
        ret["media_url"]=Json::Value();
    }
    if(getMediaThumbUrl())
    {
        ret["media_thumb_url"]=getValueOfMediaThumbUrl();
    }
    else
    {
        ret["media_thumb_url"]=Json::Value();
    }
    if(getMediaSize())
    {
        ret["media_size"]=(Json::Int64)getValueOfMediaSize();
    }
    else
    {
        ret["media_size"]=Json::Value();
    }
    if(getMediaDuration())
    {
        ret["media_duration"]=getValueOfMediaDuration();
    }
    else
    {
        ret["media_duration"]=Json::Value();
    }
    if(getMediaFormat())
    {
        ret["media_format"]=getValueOfMediaFormat();
    }
    else
    {
        ret["media_format"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getExpireTime())
    {
        ret["expire_time"]=getExpireTime()->toDbStringLocal();
    }
    else
    {
        ret["expire_time"]=Json::Value();
    }
    return ret;
}

bool OfflineMessage::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("from_user_id"))
    {
        if(!validJsonOfField(1, "from_user_id", pJson["from_user_id"], err, true))
            return false;
    }
    else
    {
        err="The from_user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("to_user_id"))
    {
        if(!validJsonOfField(2, "to_user_id", pJson["to_user_id"], err, true))
            return false;
    }
    else
    {
        err="The to_user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("chat_type"))
    {
        if(!validJsonOfField(3, "chat_type", pJson["chat_type"], err, true))
            return false;
    }
    else
    {
        err="The chat_type column cannot be null";
        return false;
    }
    if(pJson.isMember("target_id"))
    {
        if(!validJsonOfField(4, "target_id", pJson["target_id"], err, true))
            return false;
    }
    else
    {
        err="The target_id column cannot be null";
        return false;
    }
    if(pJson.isMember("msg_type"))
    {
        if(!validJsonOfField(5, "msg_type", pJson["msg_type"], err, true))
            return false;
    }
    else
    {
        err="The msg_type column cannot be null";
        return false;
    }
    if(pJson.isMember("content"))
    {
        if(!validJsonOfField(6, "content", pJson["content"], err, true))
            return false;
    }
    if(pJson.isMember("media_url"))
    {
        if(!validJsonOfField(7, "media_url", pJson["media_url"], err, true))
            return false;
    }
    if(pJson.isMember("media_thumb_url"))
    {
        if(!validJsonOfField(8, "media_thumb_url", pJson["media_thumb_url"], err, true))
            return false;
    }
    if(pJson.isMember("media_size"))
    {
        if(!validJsonOfField(9, "media_size", pJson["media_size"], err, true))
            return false;
    }
    if(pJson.isMember("media_duration"))
    {
        if(!validJsonOfField(10, "media_duration", pJson["media_duration"], err, true))
            return false;
    }
    if(pJson.isMember("media_format"))
    {
        if(!validJsonOfField(11, "media_format", pJson["media_format"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(12, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("expire_time"))
    {
        if(!validJsonOfField(13, "expire_time", pJson["expire_time"], err, true))
            return false;
    }
    return true;
}
bool OfflineMessage::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool OfflineMessage::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("from_user_id"))
    {
        if(!validJsonOfField(1, "from_user_id", pJson["from_user_id"], err, false))
            return false;
    }
    if(pJson.isMember("to_user_id"))
    {
        if(!validJsonOfField(2, "to_user_id", pJson["to_user_id"], err, false))
            return false;
    }
    if(pJson.isMember("chat_type"))
    {
        if(!validJsonOfField(3, "chat_type", pJson["chat_type"], err, false))
            return false;
    }
    if(pJson.isMember("target_id"))
    {
        if(!validJsonOfField(4, "target_id", pJson["target_id"], err, false))
            return false;
    }
    if(pJson.isMember("msg_type"))
    {
        if(!validJsonOfField(5, "msg_type", pJson["msg_type"], err, false))
            return false;
    }
    if(pJson.isMember("content"))
    {
        if(!validJsonOfField(6, "content", pJson["content"], err, false))
            return false;
    }
    if(pJson.isMember("media_url"))
    {
        if(!validJsonOfField(7, "media_url", pJson["media_url"], err, false))
            return false;
    }
    if(pJson.isMember("media_thumb_url"))
    {
        if(!validJsonOfField(8, "media_thumb_url", pJson["media_thumb_url"], err, false))
            return false;
    }
    if(pJson.isMember("media_size"))
    {
        if(!validJsonOfField(9, "media_size", pJson["media_size"], err, false))
            return false;
    }
    if(pJson.isMember("media_duration"))
    {
        if(!validJsonOfField(10, "media_duration", pJson["media_duration"], err, false))
            return false;
    }
    if(pJson.isMember("media_format"))
    {
        if(!validJsonOfField(11, "media_format", pJson["media_format"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(12, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("expire_time"))
    {
        if(!validJsonOfField(13, "expire_time", pJson["expire_time"], err, false))
            return false;
    }
    return true;
}
bool OfflineMessage::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool OfflineMessage::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
User OfflineMessage::getUser(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from user where id = ?";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *toUserId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return User(r[0]);
}

void OfflineMessage::getUser(const DbClientPtr &clientPtr,
                             const std::function<void(User)> &rcb,
                             const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from user where id = ?";
    *clientPtr << sql
               << *toUserId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(User(r[0]));
                    }
               }
               >> ecb;
}
