/**
 *
 *  User.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace yaroserverdb
{
class Device;
class Friend;
class FriendRequest;
class Group;
class GroupMember;
class Moment;
class OfflineMessage;

class User
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _username;
        static const std::string _phone;
        static const std::string _email;
        static const std::string _password_hash;
        static const std::string _nickname;
        static const std::string _avatar_url;
        static const std::string _cover_url;
        static const std::string _gender;
        static const std::string _birth_date;
        static const std::string _region;
        static const std::string _signature;
        static const std::string _status;
        static const std::string _last_login_time;
        static const std::string _last_login_ip;
        static const std::string _created_at;
        static const std::string _updated_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit User(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit User(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    User(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    User() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;

    /**  For column username  */
    ///Get the value of the column username, returns the default value if the column is null
    const std::string &getValueOfUsername() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUsername() const noexcept;
    ///Set the value of the column username
    void setUsername(const std::string &pUsername) noexcept;
    void setUsername(std::string &&pUsername) noexcept;

    /**  For column phone  */
    ///Get the value of the column phone, returns the default value if the column is null
    const std::string &getValueOfPhone() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPhone() const noexcept;
    ///Set the value of the column phone
    void setPhone(const std::string &pPhone) noexcept;
    void setPhone(std::string &&pPhone) noexcept;
    void setPhoneToNull() noexcept;

    /**  For column email  */
    ///Get the value of the column email, returns the default value if the column is null
    const std::string &getValueOfEmail() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEmail() const noexcept;
    ///Set the value of the column email
    void setEmail(const std::string &pEmail) noexcept;
    void setEmail(std::string &&pEmail) noexcept;
    void setEmailToNull() noexcept;

    /**  For column password_hash  */
    ///Get the value of the column password_hash, returns the default value if the column is null
    const std::string &getValueOfPasswordHash() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPasswordHash() const noexcept;
    ///Set the value of the column password_hash
    void setPasswordHash(const std::string &pPasswordHash) noexcept;
    void setPasswordHash(std::string &&pPasswordHash) noexcept;

    /**  For column nickname  */
    ///Get the value of the column nickname, returns the default value if the column is null
    const std::string &getValueOfNickname() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getNickname() const noexcept;
    ///Set the value of the column nickname
    void setNickname(const std::string &pNickname) noexcept;
    void setNickname(std::string &&pNickname) noexcept;

    /**  For column avatar_url  */
    ///Get the value of the column avatar_url, returns the default value if the column is null
    const std::string &getValueOfAvatarUrl() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAvatarUrl() const noexcept;
    ///Set the value of the column avatar_url
    void setAvatarUrl(const std::string &pAvatarUrl) noexcept;
    void setAvatarUrl(std::string &&pAvatarUrl) noexcept;
    void setAvatarUrlToNull() noexcept;

    /**  For column cover_url  */
    ///Get the value of the column cover_url, returns the default value if the column is null
    const std::string &getValueOfCoverUrl() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCoverUrl() const noexcept;
    ///Set the value of the column cover_url
    void setCoverUrl(const std::string &pCoverUrl) noexcept;
    void setCoverUrl(std::string &&pCoverUrl) noexcept;
    void setCoverUrlToNull() noexcept;

    /**  For column gender  */
    ///Get the value of the column gender, returns the default value if the column is null
    const int8_t &getValueOfGender() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int8_t> &getGender() const noexcept;
    ///Set the value of the column gender
    void setGender(const int8_t &pGender) noexcept;
    void setGenderToNull() noexcept;

    /**  For column birth_date  */
    ///Get the value of the column birth_date, returns the default value if the column is null
    const ::trantor::Date &getValueOfBirthDate() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getBirthDate() const noexcept;
    ///Set the value of the column birth_date
    void setBirthDate(const ::trantor::Date &pBirthDate) noexcept;
    void setBirthDateToNull() noexcept;

    /**  For column region  */
    ///Get the value of the column region, returns the default value if the column is null
    const std::string &getValueOfRegion() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRegion() const noexcept;
    ///Set the value of the column region
    void setRegion(const std::string &pRegion) noexcept;
    void setRegion(std::string &&pRegion) noexcept;
    void setRegionToNull() noexcept;

    /**  For column signature  */
    ///Get the value of the column signature, returns the default value if the column is null
    const std::string &getValueOfSignature() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSignature() const noexcept;
    ///Set the value of the column signature
    void setSignature(const std::string &pSignature) noexcept;
    void setSignature(std::string &&pSignature) noexcept;
    void setSignatureToNull() noexcept;

    /**  For column status  */
    ///Get the value of the column status, returns the default value if the column is null
    const int8_t &getValueOfStatus() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int8_t> &getStatus() const noexcept;
    ///Set the value of the column status
    void setStatus(const int8_t &pStatus) noexcept;
    void setStatusToNull() noexcept;

    /**  For column last_login_time  */
    ///Get the value of the column last_login_time, returns the default value if the column is null
    const ::trantor::Date &getValueOfLastLoginTime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getLastLoginTime() const noexcept;
    ///Set the value of the column last_login_time
    void setLastLoginTime(const ::trantor::Date &pLastLoginTime) noexcept;
    void setLastLoginTimeToNull() noexcept;

    /**  For column last_login_ip  */
    ///Get the value of the column last_login_ip, returns the default value if the column is null
    const std::string &getValueOfLastLoginIp() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLastLoginIp() const noexcept;
    ///Set the value of the column last_login_ip
    void setLastLoginIp(const std::string &pLastLoginIp) noexcept;
    void setLastLoginIp(std::string &&pLastLoginIp) noexcept;
    void setLastLoginIpToNull() noexcept;

    /**  For column created_at  */
    ///Get the value of the column created_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreatedAt() const noexcept;
    ///Set the value of the column created_at
    void setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept;
    void setCreatedAtToNull() noexcept;

    /**  For column updated_at  */
    ///Get the value of the column updated_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfUpdatedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getUpdatedAt() const noexcept;
    ///Set the value of the column updated_at
    void setUpdatedAt(const ::trantor::Date &pUpdatedAt) noexcept;
    void setUpdatedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 17;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    std::vector<Device> getDevice(const drogon::orm::DbClientPtr &clientPtr) const;
    void getDevice(const drogon::orm::DbClientPtr &clientPtr,
                   const std::function<void(std::vector<Device>)> &rcb,
                   const drogon::orm::ExceptionCallback &ecb) const;
    std::vector<Friend> getFriend(const drogon::orm::DbClientPtr &clientPtr) const;
    void getFriend(const drogon::orm::DbClientPtr &clientPtr,
                   const std::function<void(std::vector<Friend>)> &rcb,
                   const drogon::orm::ExceptionCallback &ecb) const;
    std::vector<FriendRequest> getFriendRequest(const drogon::orm::DbClientPtr &clientPtr) const;
    void getFriendRequest(const drogon::orm::DbClientPtr &clientPtr,
                          const std::function<void(std::vector<FriendRequest>)> &rcb,
                          const drogon::orm::ExceptionCallback &ecb) const;
    std::vector<Group> getGroup(const drogon::orm::DbClientPtr &clientPtr) const;
    void getGroup(const drogon::orm::DbClientPtr &clientPtr,
                  const std::function<void(std::vector<Group>)> &rcb,
                  const drogon::orm::ExceptionCallback &ecb) const;
    std::vector<GroupMember> getGroupMember(const drogon::orm::DbClientPtr &clientPtr) const;
    void getGroupMember(const drogon::orm::DbClientPtr &clientPtr,
                        const std::function<void(std::vector<GroupMember>)> &rcb,
                        const drogon::orm::ExceptionCallback &ecb) const;
    std::vector<OfflineMessage> getOfflineMessage(const drogon::orm::DbClientPtr &clientPtr) const;
    void getOfflineMessage(const drogon::orm::DbClientPtr &clientPtr,
                           const std::function<void(std::vector<OfflineMessage>)> &rcb,
                           const drogon::orm::ExceptionCallback &ecb) const;
    std::vector<Moment> getMoment(const drogon::orm::DbClientPtr &clientPtr) const;
    void getMoment(const drogon::orm::DbClientPtr &clientPtr,
                   const std::function<void(std::vector<Moment>)> &rcb,
                   const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<User>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<User>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<std::string> username_;
    std::shared_ptr<std::string> phone_;
    std::shared_ptr<std::string> email_;
    std::shared_ptr<std::string> passwordHash_;
    std::shared_ptr<std::string> nickname_;
    std::shared_ptr<std::string> avatarUrl_;
    std::shared_ptr<std::string> coverUrl_;
    std::shared_ptr<int8_t> gender_;
    std::shared_ptr<::trantor::Date> birthDate_;
    std::shared_ptr<std::string> region_;
    std::shared_ptr<std::string> signature_;
    std::shared_ptr<int8_t> status_;
    std::shared_ptr<::trantor::Date> lastLoginTime_;
    std::shared_ptr<std::string> lastLoginIp_;
    std::shared_ptr<::trantor::Date> createdAt_;
    std::shared_ptr<::trantor::Date> updatedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[17]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "username,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "phone,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "email,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "password_hash,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "nickname,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "avatar_url,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "cover_url,";
            ++parametersCount;
        }
        sql += "gender,";
        ++parametersCount;
        if(!dirtyFlag_[8])
        {
            needSelection=true;
        }
        if(dirtyFlag_[9])
        {
            sql += "birth_date,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "region,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "signature,";
            ++parametersCount;
        }
        sql += "status,";
        ++parametersCount;
        if(!dirtyFlag_[12])
        {
            needSelection=true;
        }
        if(dirtyFlag_[13])
        {
            sql += "last_login_time,";
            ++parametersCount;
        }
        if(dirtyFlag_[14])
        {
            sql += "last_login_ip,";
            ++parametersCount;
        }
        sql += "created_at,";
        ++parametersCount;
        if(!dirtyFlag_[15])
        {
            needSelection=true;
        }
        sql += "updated_at,";
        ++parametersCount;
        if(!dirtyFlag_[16])
        {
            needSelection=true;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        sql +="default,";
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[9])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[10])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[11])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[12])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[13])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[14])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[15])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[16])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace yaroserverdb
} // namespace drogon_model
